#!/bin/sh
### BEGIN INIT INFO
# Provides:          raspberry-radio-printer-xively 
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Reports every minute the current system data to xively
# Description:       Reports every minute the current system data to xively 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export FEED_ID=1564392427
export API_KEY=changeThis
export DEBUG=false

do_start () {
 start-stop-daemon --start --chuid pi --background --oknodo --exec /home/pi/RaspberryRadioPrinter/.envs/venv/bin/python /home/pi/RaspberryRadioPrinter/RaspberryRadioXively.py
}

do_stop () {
 start-stop-daemon --stop --oknodo --exec /home/pi/RaspberryRadioPrinter/.envs/venv/bin/python /home/pi/RaspberryRadioPrinter/RaspberryRadioXively.py
}

do_status () {
 return 0
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	do_stop
        do_start
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: raspberry-radio-printer-xively [start|stop|status]" >&2
	exit 3
	;;
esac

